# -*- coding: utf-8 -*-
"""Gpr-Deneme1.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L68gYnVUvbA1nfhl4yYwOzPKnRaNoC7W
"""

# !pip install impdar
# !pip install h5py
# !pip install segyio

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 300
# %config InlineBackend.figure_format = 'retina'

# Commented out IPython magic to ensure Python compatibility.
# %pip install glob2

import glob
files = glob.glob('sample_data/*')


# Impdar's loading function
from impdar.lib import load
print(files)
dat = load.load_olaf.load_olaf(files)

dat.save('test_data_raw.mat')

# Impdar's plotting function
from impdar.lib.plot import plot_traces, plot_radargram
# %matplotlib inline
plot_radargram(dat)

dat = load.load_olaf.load_olaf(files)
dat2 = load.load_olaf.load_olaf(files)

plot_traces(dat,tr=100)

"""***BAND PASS FILTER(DENEME-1)***"""

dat.vertical_band_pass(1,5)
dat2.vertical_band_pass(1,5)

dat.save('./test_data_bandpassed.mat')

plot_traces(dat, tr=100)

plot_radargram(dat)

"""***Geometric Correction--Depth***"""

dat.crop(0.,dimension='pretrig')
dat.nmo(160)
dat2.crop(0.,dimension='pretrig')
dat2.nmo(160)
dat.save('test_data_nmo.mat')
plot_radargram(dat, ydat='depth')

from impdar.lib.gpslib import interp
interp([dat],8)
interp([dat2],8)

# Save and plot the interpolated image
dat.save('test_data_interp.mat')
plot_radargram(dat,ydat='depth',xdat='dist',x_range=(0,500))

"""***Gürültü Azaltma-Wiener filter***"""

dat.denoise(1,15)
dat2.denoise(1,150)
dat.save('test_data_denoise.mat')
plot_radargram(dat,ydat='depth',xdat='dist',x_range=(0,600))
plot_radargram(dat2,ydat='depth',xdat='dist',x_range=(0,600))

"""***Linear Range Gain-Sinyal arttırma***"""

dat.rangegain(0.05)
dat2.rangegain(1.05)

# Save and plot
dat.save('test_data_gain.mat')
plot_radargram(dat,ydat='depth',xdat='dist',x_range=(0,600))
plot_radargram(dat2,ydat='depth',xdat='dist',x_range=(0,600))
